// export const API_URL = process.env.API_URL;
export const STAGE = process.env.REACT_APP_API_STAGE;
export const APIGATEWAY_URL = process.env.REACT_APP_API_APIGATEWAY_URL;
export const API_URL = `${APIGATEWAY_URL}/${STAGE}`;
// src/constants/apiConstants.js

export const API_BASE_URL = process.env.REACT_APP_API_BASE_URL;
export const GET_ROOM_DETAILS = `${API_URL}/api/rooms`;
export const UPDATE_ROOM_DETAILS = `${API_URL}/api/rooms`;
export const ADD_ROOM = `${API_URL}/api/rooms`;
export const GET_ROOMS = `${API_URL}/api/rooms`;
export const ROOMS_ENDPOINT = `${API_URL}/api/rooms`;
export const options = [
  { id: 1, question: "What was the name of your first pet?" },
  { id: 2, question: "What is the name of the town where you were born?" },
  { id: 3, question: "What was your childhood nickname?" },
  { id: 4, question: "What is your mother's maiden name?" },
  { id: 5, question: "What was the name of your elementary school?" },
  { id: 6, question: "What is the name of your favorite teacher?" },
];

export const words = [
  "apple",
  "banana",
  "grape",
  "orange",
  "strawberry",
  "blueberry",
  "pineapple",
  "watermelon",
  "kiwi",
  "mango",
  "lemon",
  "lime",
  "cherry",
  "peach",
  "plum",
  "pear",
  "apricot",
  "blackberry",
  "raspberry",
  "cantaloupe",
  "honeydew",
  "fig",
  "pomegranate",
  "coconut",
  "guava",
  "papaya",
  "passionfruit",
  "persimmon",
  "quince",
  "tangerine",
  "nectarine",
  "cranberry",
  "mulberry",
  "boysenberry",
  "lychee",
  "dragonfruit",
  "durian",
  "jackfruit",
  "starfruit",
  "kumquat",
  "carrot",
  "potato",
  "tomato",
  "onion",
  "garlic",
  "broccoli",
  "cauliflower",
  "spinach",
  "lettuce",
  "cabbage",
  "kale",
  "zucchini",
  "cucumber",
  "peas",
  "chili",
  "pepper",
  "radish",
  "turnip",
  "beet",
  "eggplant",
  "pumpkin",
  "squash",
  "yam",
  "pizza",
  "corn",
  "pea",
  "bean",
  "lentil",
  "chickpea",
  "soybean",
  "rice",
  "wheat",
  "barley",
  "oat",
  "rye",
  "quinoa",
  "millet",
  "buckwheat",
  "amaranth",
  "sorghum",
  "chicken",
  "beef",
  "pork",
  "lamb",
  "fish",
  "shrimp",
  "crab",
  "lobster",
  "clam",
  "mussel",
  "oyster",
  "scallop",
  "squid",
  "octopus",
  "salmon",
  "tuna",
  "trout",
  "cod",
  "herring",
  "sardine",
];

export const rooms = [
  {
    id: "03e2beee-2245-44f2-bcce-ec4d8c20004b",
    name: "JW Marriott Inn",
    price: "$50",
    roomAddress: "Downtown, Halifax, Nova Scotia",
    imageSrc:
      "https://images.pexels.com/photos/271639/pexels-photo-271639.jpeg",
    imageAlt: "Black and white photo of hotel room",
    bedroomCount: 2,
    bathroomCount: 1,
    amenities: [
      "Free Wi-Fi",
      "Air Conditioning",
      "Flat Screen TV",
      "Mini Bar",
      "Room Service",
    ],
  },
  {
    id: "03e2beee-2245-44f2-bcce-ec4d8c20004b",
    name: "Hilton Garden Inn",
    price: "$140",
    roomAddress: "Downtown, Halifax, Nova Scotia",
    imageSrc:
      "https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg",
    imageAlt: "Black and white photo of hotel room",
    bedroomCount: 2,
    bathroomCount: 1,
    amenities: [
      "Free Wi-Fi",
      "Air Conditioning",
      "Flat Screen TV",
      "Mini Bar",
      "Room Service",
    ],
  },
  {
    id: "03e2beee-2245-44f2-bcce-ec4d8c20004b",
    name: "Hilton Garden Inn",
    price: "$220",
    roomAddress: "Downtown, Halifax, Nova Scotia",
    imageSrc:
      "https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    imageAlt: "Room with black walls and white bed",
    bedroomCount: 2,
    bathroomCount: 1,
    amenities: [
      "Free Wi-Fi",
      "Air Conditioning",
      "Flat Screen TV",
      "Mini Bar",
      "Room Service",
    ],
  },
];

export const agentRooms = [
  {
    id: 1,
    image: "https://images.pexels.com/photos/271639/pexels-photo-271639.jpeg",
    bedroomCount: 2,
    bathroomCount: 1,
    amenities: [
      "Free Wi-Fi",
      "Air Conditioning",
      "Flat Screen TV",
      "Mini Bar",
      "Room Service",
    ],
    description:
      "A cozy room with two bedrooms and modern amenities. Perfect for families or small groups.",
    pricePerNight: 120,
    available: true,
    location: "Downtown",
    rating: 4.5,
  },
  {
    id: 2,
    image: "https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg",
    bedroomCount: 1,
    bathroomCount: 1,
    amenities: [
      "Free Wi-Fi",
      "Air Conditioning",
      "Flat Screen TV",
      "Room Service",
      "Balcony",
    ],
    description:
      "A luxurious room with a beautiful view and modern amenities. Ideal for couples.",
    pricePerNight: 150,
    available: true,
    location: "Beachfront",
    rating: 4.8,
  },
  {
    id: 3,
    image:
      "https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    bedroomCount: 3,
    bathroomCount: 2,
    amenities: [
      "Free Wi-Fi",
      "Air Conditioning",
      "Flat Screen TV",
      "Mini Bar",
      "Room Service",
      "Kitchenette",
    ],
    description:
      "A spacious room with three bedrooms and a kitchenette. Perfect for large groups or families.",
    pricePerNight: 200,
    available: false,
    location: "Suburbs",
    rating: 4.2,
  },
  {
    id: 4,
    image:
      "https://as1.ftcdn.net/v2/jpg/02/71/08/28/1000_F_271082810_CtbTjpnOU3vx43ngAKqpCPUBx25udBrg.jpg",
    bedroomCount: 1,
    bathroomCount: 1,
    amenities: [
      "Free Wi-Fi",
      "Air Conditioning",
      "Flat Screen TV",
      "Room Service",
      "Garden View",
    ],
    description:
      "A charming room with a garden view and all the modern comforts. Ideal for solo travelers or couples.",
    pricePerNight: 100,
    available: true,
    location: "Countryside",
    rating: 4.7,
  },
];

export const roomDetails = {
  roomId: "03e2beee-2245-44f2-bcce-ec4d8c20004b",
  name: "Hilton Garden Inn",
  price: "$220",
  description:
    "Welcome to your serene retreat at the Hilton Garden Inn, perfectly suited for both relaxation and productivity. This inviting room is part of the renowned Hilton Garden Inn, known for its comfort and modern amenities.",
  imageSrc: "https://images.pexels.com/photos/271639/pexels-photo-271639.jpeg",
  imageAlt: "Room with black walls and white bed",
  bedroomCount: 2,
  bathroomCount: 1,
  amenities: [
    "Free Wi-Fi",
    "Air Conditioning",
    "Flat Screen TV",
    "Mini Bar",
    "Room Service",
  ],
  roomAddress: "Downtown, Halifax, Nova Scotia",
  bedroomCount: 2,
  bathroomCount: 1,
  type: "Deluxe",
  reviews: [
    {
      id: 1,
      rating: 5,
      author: "Emily Selman",
      timestamp: 1533280000000,
      commentHeading: "Great stay!",
      comment:
        "This room is fantastic! The decor is stylish and modern, and the bed is incredibly comfortable. Highly recommend!",
    },
    {
      id: 2,
      rating: 4,
      timestamp: 1533280000000,
      author: "Hector Gibbons",
      commentHeading: "Clean and comfortable",
      comment:
        "Great location and very clean. The host was friendly and responsive. Only minor issue was the street noise at night.",
    },
    {
      id: 3,
      rating: 5,
      timestamp: 1533280000000,
      author: "Sarah James",
      commentHeading: "Amazing view",
      comment:
        "Absolutely loved staying here. The amenities were top-notch, and the view from the balcony is breathtaking. Will definitely be back!",
    },
    {
      id: 4,
      rating: 3,
      timestamp: 1533280000000,
      author: "Jason Meyers",
      commentHeading: "Overall experience",
      comment:
        "The room was nice, but it didn't quite meet my expectations based on the photos. Still a decent stay overall.",
    },
    {
      id: 5,
      rating: 4,
      timestamp: 1533280000000,
      author: "Emily Selman",
      commentHeading: "Overall experience",
      comment:
        "Clean and cozy room with all the essentials. Good value for money and the check-in process was smooth.",
    },
  ],
};
